language: node.js


node_js:
  - "10.9.0"

cache : npm

before_install:
#create a dicrectory named dist
-mkdir dist
#change into dist 
-cd dist
#list all operation
-ls -la

install:
-ls -la
#Install dependencies
-npm install 
-ls -la




