
language: node_js
node_js:
  - 10.9.0
cache: npm
before_install:
- ls -la
- npm install
- "npm config set spin false"
- npm i -g now

script:
- npm run build
- npm run test

deploy:
  provider: scripts 
  script: bash scripts/deploy.sh
  skip_cleanup:true
  
    
